### ISSUE TITLE
React native: Cannot connect by android

### ISSUE THREAD

**Issue by sy92th** [jmesnil/stomp-websocket#141]
My app use last version and client always return Whoops! Lost connection
Please help me.

Mycode:

var Stomp = require('stompjs/lib/stomp.js').Stomp;
let client = Stomp.client(url);
client.connect({}, function connectCallback(frame){
console.log('OK')
}, (error) => {
console.log('Error');
});

It work very good in ios but in android:
Web Socket Opened...
>>> CONNECT
accept-version:1.1,1.0
heart-beat:10000,10000

Whoops! Lost connection
Error

**Comment by kashsbd** [comment]
I encounter the same error too !

**Comment by phanvudinh** [comment]
it's same to me.

**Comment by zhaoji223** [comment]
I use stomp.js(version:  1.7.1) and sockjs(v: 1.1.4). React Native (version: 0.52.0).   Android not work to,   because it's  sockjs bug.  ---->>>> Fix it reference:  https://github.com/sockjs/sockjs-client/issues/365   ------>>>>  PavelJ commented on 21 Aug 2017.   It work very good in android. @phanvudinh  @B4UGUYS  @sy92th

**Comment by kashsbd** [comment]
Thanks @zhaoji223

**Comment by sy92th** [comment]
@zhaoji223 I can't get stomp.js (version: 1.7.1) 
```
CMD: npm view stompjs versions
Printout: [ '2.1.0-next', '2.2.0', '2.3.0', '2.3.1', '2.3.2', '2.3.3' ]
```
and when I use last version of stomp.js, I can't connect by both ( android and iOS)

```
var socket = new SockJS(url);
stompClient = Stomp.over(socket);
client.connect({}, function connectCallback(frame){
    console.log('OK')
}, (error) => {
    console.log('Error');
});
```

**Comment by zhaoji223** [comment]
[sockjs.min.txt](https://github.com/jmesnil/stomp-websocket/files/1695448/sockjs.min.txt)
[stomp.txt](https://github.com/jmesnil/stomp-websocket/files/1695449/stomp.txt)

rename to .js  -->    stomp and sockjs old version .  O_0  o_O    @sy92th

**Comment by sy92th** [comment]
Thank @zhaoji223  but it still does not work.
I'm using the url 'ws: // ....' and have error from sockjs:
`SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed.`

When I change url to 'http://...' I can't connect by both ( android and iOS)
```
Opening Web Socket...
Whoops! Lost connection to
```

 I'm using Spring-boot for server. When I only use Stomp it work very good in iOS but not working in android

**Comment by phanvudinh** [comment]
I used stompjs(version 2.3.3) and sockjs-client(version 1.1.4). It works perfectly!
I think @sy92th have two cases:
- The first: When you write on IOS. We don't need using sockjs-client. Everything are done by stompjs and endpoint's URL something like this 'http:hostname:port/end-point/**websocket**'. Postfix **websocket** always have.(I didn't test when i use both socket-client and stompjs together on IOS, but i think that it works well. See the second thing.)
- The second: that is the rest. When write in Android. We need both stompjs and sockjs-client. Note that we don't need postfix **websocket** anymore. Because that is done by sockjs-client automatically, you can check it. But it's not enough, you must fix bug that @zhaoji223 commented. Then it's ok. I guess you get 

> Opening Web Socket...
> Whoops! Lost connection to

error from forgot delete **websocket** in URL right?

Thank @zhaoji223 one more time. :dancing_men: :dancer:

**Comment by sy92th** [comment]
I forgot remove **websocket** in URL =)
Thank @phanvudinh  and @zhaoji223 one more time.
This work.

**Comment by VladyslavVasylenko1996** [comment]
I have same problem,  when I use Android < 7.0.Can you help me please?

**Comment by rahuluvionics** [comment]
Hi, I am also stuck while implementing stomp in React native. No callback has received. Can anyone got it implemented successfully?

**Comment by Malikkhoja-zz** [comment]
I used stompjs(version 2.3.3) and sockjs-client(version 1.1.4) on React Native 0.62.2

It doesnt work.
>>> CONNECT
accept-version:1.1,1.0
heart-beat:5000,5000
Whoops lost connection to url

Can anyone help?

**Comment by StefanoMartella** [comment]
Hi, in my case the problem was that I was using `http://localhost:8080/chat` as websocket url; since I'm on an Android emulator I had to use `http://10.0.2.2:8080/chat` instead. More details here:
https://stackoverflow.com/a/5495789/9121838
